const seriesTypes: string[] = [
  'arcdiagram',
  'area',
  'arearange',
  'areaspline',
  'areasplinerange',
  'bar',
  'bellcurve',
  'boxplot',
  'bubble',
  'bullet',
  'column',
  'columnpyramid',
  'cylinder',
  'dependencywheel',
  'dumbbell',
  'errorbar',
  'funnel',
  'funnel3d',
  'gauge',
  'heatmap',
  'histogram',
  'item',
  'line',
  'lollipop',
  // 'networkgraph', HOLDING OUT DUE TO HIGH COMPLEXITY
  'organization',
  'packedbubble',
  'pareto',
  'pie',
  'polygon',
  'pyramid',
  'pyramid3d',
  'sankey',
  'scatter',
  // 'scatter3d', HOLDING OUT DUE TO HIGH COMPLEXITY
  'solidgauge',
  'spline',
  'streamgraph',
  'sunburst',
  'timeline',
  'treegraph',
  'treemap',
  'variablepie',
  'variwide',
  'vector',
  'venn',
  'windbarb',
  'wordcloud',
  'xrange',
];

export default seriesTypes;
